### ISSUE TITLE
Global Error Catch (Utilities)

### ISSUE THREAD

**Issue by clarkiness72** [RobertPorterfield/SBO-Workflow#8]
Implement a global error catcher that will automatically attempt to log the error to a SP List.

*Check with Kelly to see if this is actually used.

**Comment by clarkiness72** [comment]
This is never used by Kelly or any other SBO personnel so it was likely only ever used by Vana for debugging issues in Prod. I can see the value in having this but I do not think it needs to be a high priority or even in the MVP for this rewrite. We can add this functionality later if we deem it necessary, until then I am going to drop it to the bottom of the backlog.

**Comment by RobertPorterfield** [comment]
This is not needed. Errors are reported to the user. Any errors that should be caught and stored here are likely app breaking errors that would prevent them from being reported back to SharePoint anyhow
